// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdN_JIxtnvxhfiCMISUPiGKDyfkqIPyvI',
    appId: '1:927869658058:web:2722782ad469736a8ba533',
    messagingSenderId: '927869658058',
    projectId: 'lab-final-pos',
    authDomain: 'lab-final-pos.firebaseapp.com',
    storageBucket: 'lab-final-pos.firebasestorage.app',
    measurementId: 'G-8ZY9B35DWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5_0ufRKfoWgJ5Tju50u0eYztBEd2eas',
    appId: '1:927869658058:android:eba1d7a9236a4d728ba533',
    messagingSenderId: '927869658058',
    projectId: 'lab-final-pos',
    storageBucket: 'lab-final-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9T1pzQ3KNJiep6yKGrQoSZe57YefZmQ4',
    appId: '1:927869658058:ios:3daa5daa4ad8ee708ba533',
    messagingSenderId: '927869658058',
    projectId: 'lab-final-pos',
    storageBucket: 'lab-final-pos.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9T1pzQ3KNJiep6yKGrQoSZe57YefZmQ4',
    appId: '1:927869658058:ios:3daa5daa4ad8ee708ba533',
    messagingSenderId: '927869658058',
    projectId: 'lab-final-pos',
    storageBucket: 'lab-final-pos.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdN_JIxtnvxhfiCMISUPiGKDyfkqIPyvI',
    appId: '1:927869658058:web:9d0d55456db4707a8ba533',
    messagingSenderId: '927869658058',
    projectId: 'lab-final-pos',
    authDomain: 'lab-final-pos.firebaseapp.com',
    storageBucket: 'lab-final-pos.firebasestorage.app',
    measurementId: 'G-SPF2FTWRHR',
  );
}
